name: Python Package using Conda

on: [push]

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.1
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - run: pip install -U pytest 
    #- run: pip install -r requirements.txt
    #- run: python -m pytest tests
    - name: Test with pytest
      run: |
       pytest
