name: Python Package using Conda

on: [push]

jobs:
  test_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.1

    - run: pip install -U pytest 
    - run:
          pip install streamlit
          pip install joblib
          pip install scikit-learn
  
          
    - run: python build_model.py
    
    - name: Upload model artifact

      uses: actions/upload-artifact@v3
      with:
        path: regression.joblib
          
    - name: Test with pytest
      run: pytest tes1.py

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
